### ISSUE TITLE
How to keep graph stable?

### ISSUE THREAD

**Issue by chrisco23** [rncbc/qpwgraph#10]
Hi,

I am just trying to get to a stable graph view for a very basic setup.  

I brought this up before and the advice I got about Zoom Fit and Zoom Range helped, but it's still causing me some grief and I'm wondering what I could be doing wrong.

I have an io4 soundcard which receives a simple input from Strawberry, Chromium, whatever.

I will at some point have 1 or 2 MIDI keyboards attached but that's about the extent of it.

Now, I have one saved graph, called "sound".  But in the linked video, this is about what I have to go through every time I need to start up qpwgraph.

I can see in watching this video that maybe the biggest mistake I made was not deselecting the Zoom Range.

But what else can I do here?  Surely I don't need to spend 9 minutes every time I need to start qpwgraph.

https://youtu.be/PtC1AbScX8k

**Comment by rncbc** [comment]
hi, my first suggestion would be to to get away with the whole "annoying" old positioning and configuration file: while qpwgraph is not running--menu Graph > Quit if it is--remove or move away the `~/.config/rncbc.org/qpwgraph.conf` and start qpwgraph again so that the initial positioning of the existing nodes follows in more approachable layout.

you may still change the positioning and it should be remembered next time you run qpwgraph; but please keep the nodes near to the center and avoid moving any  to the current edge-limits; once you place a node over the drag limits, those limits will get adjusted accordingly making it larger and larger ultimately making the whole scene unbearable to manage as it seems to be your situation as seen in the video--you probably forgot to repositioning at least one single node way way to far from the others.

it also depends on which version of both qpwgraph and Qt you're actually running: earlier versions were prone to this kind of mischief, having no limits to where to could move a node box around and auto-scrolling where also too much accelerated while dragging stuff around.

make sure you run the latest and greatest :)

hth.
cheers

**Comment by chrisco23** [comment]
Thank you!  I didn't even know about the conf file.

After removing the conf and my previous graph file, It starts up like pictured.  This is almost perfect!  I moved one of the nodes just a bit, quit, restarted, and it remembered my adjustment.

https://pasteboard.co/SZQ0BanFqyBj.png

For reference, and I update this Arch setup daily:

qpwgraph 0.3.6
Qt: 6.4.2
libpipewire: 0.3.64 (headers: 0.3.58)

I almost wonder if it would make sense to keep things bounded such that if and when anybody really needed more room, they choose to enlarge or shrink the border as necessary.

Others with different scenarios would probably find that idea less than ideal I imagine, not sure.

For now, I'm happy!
